import { resolve } from "node:path";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { config } from "@/config.ts";
import { log } from "@/lib/utils/logger.ts";
import { resolvePath } from "@/lib/utils/path.ts";

export const registerManageDrawings = (server: McpServer) => {
	server.registerTool(
		"manage_drawings",
		{
			description: `${config.systemPrompt}\n\nCreate, update, or delete Excalidraw drawing files. Workflow for creating drawings with library components: 1) Use list_libraries to discover available libraries, 2) Use view_library to see all components in a library or filter by parameters, 3) Analyze components and decide which ones fit your drawing purpose, 4) Compose complete drawing JSON with elements from library components (adjust positions/IDs as needed) and any new elements you create, 5) Provide the complete composed JSON in the 'content' parameter. The drawing JSON should follow Excalidraw format. When copying elements from libraries, regenerate element IDs to ensure uniqueness and adjust x/y coordinates to position elements where you want them.`,
			inputSchema: {
				action: z
					.enum(["create", "update", "delete"])
					.optional()
					.default("create")
					.describe("Action to perform: create, update, or delete"),
				path: z
					.string()
					.optional()
					.describe(
						"Path to the drawing file (relative to designs directory or full filename). Required for update and delete. Optional for create - if not provided, filename will be generated from title.",
					),
				title: z
					.string()
					.optional()
					.describe(
						"Title for the design; used to generate filename for create action. Only used if path is not provided. Should already be generated by the LLM.",
					),
				content: z
					.string()
					.optional()
					.describe(
						"Excalidraw JSON or other text content. Required for create and update actions. If not provided for create, a default structure will be generated using the title.",
					),
				overwrite: z
					.boolean()
					.optional()
					.default(false)
					.describe(
						"Whether to overwrite an existing file with the same generated name. Only applies to create action. Defaults to false.",
					),
			},
		},
		async ({ action = "create", path, title, content, overwrite }) => {
			const designsDir = resolvePath(config.designsDir);

			try {
				// Ensure designs directory exists
				await Bun.$`mkdir -p ${designsDir}`.quiet();

				if (action === "delete") {
					if (!path) {
						throw new Error("Path is required for delete action");
					}

					const filename = path.endsWith(".excalidraw")
						? path
						: `${path}.excalidraw`;
					const fullPath = resolve(designsDir, filename);

					const file = Bun.file(fullPath);
					if (!(await file.exists())) {
						throw new Error(`Drawing not found: ${path}`);
					}

					await Bun.$`rm ${fullPath}`.quiet();

					await log(
						"info",
						"manage_drawings",
						{ action, path },
						`Deleted drawing: ${fullPath}`,
					);

					return {
						content: [
							{
								type: "text",
								text: JSON.stringify(
									{
										success: true,
										message: `Deleted drawing: ${path}`,
										path: fullPath,
									},
									null,
									2,
								),
							},
						],
					};
				}

				if (action === "create" || action === "update") {
					if (action === "update" && !content) {
						throw new Error("Content is required for update action");
					}

					let fullPath: string;
					let filename: string;

					if (path) {
						filename = path.endsWith(".excalidraw")
							? path
							: `${path}.excalidraw`;
						fullPath = resolve(designsDir, filename);
					} else if (title) {
						// Generate path from title (create only)
						if (action === "update") {
							throw new Error(
								"Path is required for update action. Title can only be used for create.",
							);
						}
						const now = new Date();
						const monthAbbrevs = [
							"jan",
							"feb",
							"mar",
							"apr",
							"may",
							"jun",
							"jul",
							"aug",
							"sep",
							"oct",
							"nov",
							"dec",
						] as const;
						const month = monthAbbrevs[now.getMonth()];
						const day = `${now.getDate()}`.padStart(2, "0");
						const year = `${now.getFullYear()}`.slice(-2);
						const datePrefix = `${month}${day}${year}`;

						const safeTitle =
							title
								.trim()
								.toLowerCase()
								.replace(/[^a-z0-9]+/g, "-")
								.replace(/^-+|-+$/g, "") || "untitled";
						const baseFilename = `${safeTitle}.excalidraw`;

						filename = baseFilename;
						fullPath = resolve(designsDir, filename);

						if (!overwrite) {
							let counter = 1;
							while (await Bun.file(fullPath).exists()) {
								filename = `${datePrefix}-${safeTitle}-${counter}.excalidraw`;
								fullPath = resolve(designsDir, filename);
								counter += 1;
							}
						}
					} else {
						throw new Error(
							"Either path or title must be provided for create action",
						);
					}

					if (action === "update") {
						const file = Bun.file(fullPath);
						if (!(await file.exists())) {
							throw new Error(`Drawing not found: ${path}`);
						}
					}

					// Ensure directory exists
					const dir = fullPath.substring(0, fullPath.lastIndexOf("/"));
					await Bun.$`mkdir -p ${dir}`.quiet();

					// Generate file content: use provided content, or generate default for create
					const fileContent =
						content ||
						(action === "create" && title
							? JSON.stringify(
									{
										type: "excalidraw",
										version: 1,
										source: "friday-mcp",
										title,
										createdAt: new Date().toISOString(),
									},
									null,
									2,
								)
							: null);

					if (!fileContent) {
						throw new Error(
							"Content is required. For create action, either provide content or title to generate default content.",
						);
					}

					await Bun.write(fullPath, fileContent);

					const message =
						action === "create"
							? `Created drawing: ${filename}`
							: `Updated drawing: ${filename}`;

					await log(
						"info",
						"manage_drawings",
						{ action, path, title },
						message,
					);

					return {
						content: [
							{
								type: "text",
								text: JSON.stringify(
									{
										success: true,
										message,
										filename,
										absolutePath: fullPath,
										designsDir,
									},
									null,
									2,
								),
							},
						],
					};
				}

				throw new Error(`Unknown action: ${action}`);
			} catch (error) {
				const errorMsg = `Failed to ${action} drawing: ${String(error)}`;
				await log(
					"error",
					"manage_drawings",
					{ action, path, title },
					errorMsg,
				);

				return {
					content: [
						{
							type: "text",
							text: JSON.stringify(
								{ success: false, error: errorMsg },
								null,
								2,
							),
						},
					],
				};
			}
		},
	);
};
